name: Plasmo build test
on:
  workflow_dispatch:
  pull_request: 
  # push:
  #   branches: [master,plasmo]

jobs:
  build:
    # if: github.ref_type == 'tag'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 22.13.0 ]
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
                 
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: |
          # rm -rf node_modules/ pnpm-lock.yaml
          pnpm install
          pnpm install postcss@^8 webpack@^4.0.0

      - name: Build artifacts
        run: |
            git config --global user.email "gh-action@github.com"
            git config --global user.name "gh-action"

            npm run release && head -n10 CHANGELOG.md
            make build test print-manifests
      
